### ISSUE TITLE
Textures of bit collection blocks appear to be inverted

### ISSUE THREAD

**Issue by mastery3** [CoolMineman/BitsAndChisels#143]
Screenshot: ![image](https://user-images.githubusercontent.com/94207545/202820884-dd404864-95e8-4a05-9d17-f0471a849cf3.png)

Reproduction Steps: Obtain a chiseled block in the world and compare it to it's base block

**Comment by woalk** [comment]
This is seemingly caused by [src/main/java/io/github/coolmineman/bitsandchisels/BitMeshes.java:226](https://github.com/CoolMineman/BitsAndChisels/blob/master/src/main/java/io/github/coolmineman/bitsandchisels/BitMeshes.java#L226) and seems intentional (it explicitly flips the V coordinate of the texture).

I can't really see any direct purpose for this line, simply removing it fixes the texture orientation for me. Maybe it's depending on the specific renderer?

It also seems to still struggle to place directional blocks correctly either way, like Magenta Glazed Terracotta.
