### ISSUE TITLE
[IMPROVEMENT] Bits collection blocks taking lots space. Try compression.

### ISSUE THREAD

**Issue by True-cc** [CoolMineman/BitsAndChisels#34]
Bits collection blocks take up a lot of space. It causes an incompatibility with Immersive Portals mods (and probably others). The developer tried fixing it, but didn't fully yet.
I think compressing the block data would be a good idea. I would add compressBlock and decompressBlock methods.
The first technique that comes to mind is setting a default block type to the data so at coords that don't specify a block type, set it to that default block type. It would probably make almost all blocks instantly be much smaller. Make that default block type the most used block type per block.
I hope you add this so I can continue playing on my server with immersive portals and bits and chisels. I love both mods and want to play with both of them. Thanks.

**Comment by CoolMineman** [comment]
> setting a default block type to the data so at coords that don't specify a block type, set it to that default block type
No clue what you mean by this but the existing code stores an short[][][] and a String[] Palette that maps the shorts to the BlockStates it is unclear what this default block type would do. I can try to add some compression (using a byte array instead of ShortTags?) but the nature of this mod requires large NBT.

**Comment by True-cc** [comment]
nvm
